CREATE TABLE `wp_term_relationships` (  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',  `term_order` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`object_id`,`term_taxonomy_id`),  KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `wp_term_relationships` DISABLE KEYS */;
INSERT INTO `wp_term_relationships` VALUES('1', '1', '0');
INSERT INTO `wp_term_relationships` VALUES('60', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('64', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('66', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('67', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('68', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('69', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('71', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('72', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('75', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('76', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('79', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('80', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('81', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('83', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('134', '3', '0');
INSERT INTO `wp_term_relationships` VALUES('311', '3', '0');
/*!40000 ALTER TABLE `wp_term_relationships` ENABLE KEYS */;
